#pragma once

#include "GLFW/glfw3.h"

#define BLNDR_KEY_SPACE				32
#define BLNDR_KEY_APOSTROPHE		39
#define BLNDR_KEY_COMMA				44
#define BLNDR_KEY_MINUS				45
#define BLNDR_KEY_PERIOD			46
#define BLNDR_KEY_SLASH				47
#define BLNDR_KEY_0					48
#define BLNDR_KEY_1					49
#define BLNDR_KEY_2					50
#define BLNDR_KEY_3					51
#define BLNDR_KEY_4					52
#define BLNDR_KEY_5					53
#define BLNDR_KEY_6					54
#define BLNDR_KEY_7					55
#define BLNDR_KEY_8					56
#define BLNDR_KEY_9					57
#define BLNDR_KEY_SEMICOLON			59
#define BLNDR_KEY_EQUAL				61
#define BLNDR_KEY_A					65
#define BLNDR_KEY_B					66
#define BLNDR_KEY_C					67
#define BLNDR_KEY_D					68
#define BLNDR_KEY_E					69
#define BLNDR_KEY_F					70
#define BLNDR_KEY_G					71
#define BLNDR_KEY_H					72
#define BLNDR_KEY_I					73
#define BLNDR_KEY_J					74
#define BLNDR_KEY_K					75
#define BLNDR_KEY_L					76
#define BLNDR_KEY_M					77
#define BLNDR_KEY_N					78
#define BLNDR_KEY_O					79
#define BLNDR_KEY_P					80
#define BLNDR_KEY_Q					81
#define BLNDR_KEY_R					82
#define BLNDR_KEY_S					83
#define BLNDR_KEY_T					84
#define BLNDR_KEY_U					85
#define BLNDR_KEY_V					86
#define BLNDR_KEY_W					87
#define BLNDR_KEY_X					88
#define BLNDR_KEY_Y					89
#define BLNDR_KEY_Z					90
#define BLNDR_KEY_LEFT_BRACKET		91
#define BLNDR_KEY_BACKSLASH			92
#define BLNDR_KEY_RIGHT_BRACKET		93
#define BLNDR_KEY_GRAVE_ACCENT		96
#define BLNDR_KEY_WORLD_1			161
#define BLNDR_KEY_WORLD_2			162

/* Function keys */
#define BLNDR_KEY_ESCAPE			256
#define BLNDR_KEY_ENTER				257
#define BLNDR_KEY_TAB				258
#define BLNDR_KEY_BACKSPACE			259
#define BLNDR_KEY_INSERT			260
#define BLNDR_KEY_DELETE			261
#define BLNDR_KEY_RIGHT				262
#define BLNDR_KEY_LEFT				263
#define BLNDR_KEY_DOWN				264
#define BLNDR_KEY_UP				265
#define BLNDR_KEY_PAGE_UP			266
#define BLNDR_KEY_PAGE_DOWN			267
#define BLNDR_KEY_HOME				268
#define BLNDR_KEY_END				269
#define BLNDR_KEY_CAPS_LOCK			280
#define BLNDR_KEY_SCROLL_LOCK		281
#define BLNDR_KEY_NUM_LOCK			282
#define BLNDR_KEY_PRINT_SCREEN		283
#define BLNDR_KEY_PAUSE				284
#define BLNDR_KEY_F1				290
#define BLNDR_KEY_F2				291
#define BLNDR_KEY_F3				292
#define BLNDR_KEY_F4				293
#define BLNDR_KEY_F5				294
#define BLNDR_KEY_F6				295
#define BLNDR_KEY_F7				296